"""Writes the per-target output-directory artifacts (spec section 30/38/50)."""
from __future__ import annotations

import json
from pathlib import Path

from . import common as wg_common
from .generate import GenerationResult
from .pool import WorkloadPlan


def write_dry_run_report(plan: WorkloadPlan, *, tier: str, target_text: str,
                          baseline_total_entries: int, disk_free_bytes: int = None) -> str:
    disk_gb = plan.estimated_disk_bytes / (1024 ** 3)
    L = []
    L.append(f"Target average: {target_text}")
    L.append(f"Baseline payload files: {baseline_total_entries}")
    L.append(f"Planned generated payload files: {plan.total_physical_files}")
    L.append(f"Logical requests: {baseline_total_entries}")
    L.append(f"Estimated payload disk usage: {wg_common.human_size(plan.estimated_disk_bytes)} ({disk_gb:.3f} GiB)")
    L.append(f"Estimated total disk usage: {wg_common.human_size(plan.estimated_disk_bytes)} (metadata overhead negligible)")
    if plan.missing_seed_count:
        L.append(f"Records with no resolvable source seed: {plan.missing_seed_count} "
                 f"(will use synthetic, non-representative content -- see baseline discrepancy report)")
    feasible = True
    if disk_free_bytes is not None:
        required = int(plan.estimated_disk_bytes * (1 + wg_common.DEFAULT_DISK_SAFETY_MARGIN))
        feasible = disk_free_bytes >= required
        L.append(f"Available disk: {wg_common.human_size(disk_free_bytes)}")
        L.append(f"Required (with {wg_common.DEFAULT_DISK_SAFETY_MARGIN * 100:.0f}% safety margin): "
                 f"{wg_common.human_size(required)}")
        L.append(f"Safety margin: {wg_common.DEFAULT_DISK_SAFETY_MARGIN * 100:.0f}%")
    L.append(f"Tier directory: {wg_common.output_dir_for_tier(tier)}")
    L.append(f"Result: {'FEASIBLE' if feasible else 'NOT FEASIBLE -- insufficient disk space'}")
    return "\n".join(L) + "\n"


def write_target_outputs(result: GenerationResult, manifest: dict, report: dict, *,
                          final_out_dir: Path = None) -> None:
    """Writes files into `result.output_dir` (may be a temporary staging
    directory during atomic generation -- see wg/safety.py), but the
    CONTENTS of httpstorm-config.ini/README.md reference `final_out_dir`
    (defaults to `result.output_dir` when generating directly, e.g. tests),
    since that is where the directory will actually live once any staging
    rename completes."""
    out = result.output_dir
    final_out_dir = final_out_dir or out

    (out / "diversity-report.json").write_text(json.dumps(report["diversity"], indent=2), encoding="utf-8")
    (out / "size-report.json").write_text(json.dumps(report["size"], indent=2), encoding="utf-8")
    (out / "validation-report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")

    from .validate import render_text_report
    (out / "validation-report.txt").write_text(render_text_report(report), encoding="utf-8")

    # path_root MUST be the PARENT of the tier directory (generated_<label>/),
    # not the tier directory itself -- httpblaster resolves files at exactly
    # `path_root + URI` verbatim (config.cpp::load_content_to_ram, verified in
    # source), and the resource-list URIs already start with /<label>-<tier>/,
    # so path_root pointing at the tier dir itself would double that segment.
    # This mirrors the original corpus's own doubled-root convention exactly
    # (source_root=.../<label>, URI=/<label>/...).
    label = manifest.get("workload_label", wg_common.DEFAULT_WORKLOAD_LABEL)
    path_root = final_out_dir.parent
    ini = (
        f"# HTTP Blaster / Sledgehammer config snippet for {label}-{result.tier}\n"
        f"# Source workload: {label}\n"
        f"# Generated by workload04_generator.py {wg_common.GENERATOR_VERSION}\n"
        f"\n"
        f"[sledgehammer]\n"
        f"path_file = {final_out_dir}/workload-resources.txt\n"
        f"\n"
        f"[httpblaster]\n"
        f"generate_random_content = 0\n"
        f"path_file = {final_out_dir}/workload-resources.txt\n"
        f"path_root = {path_root}\n"
    )
    (out / "httpstorm-config.ini").write_text(ini, encoding="utf-8")

    readme = (
        f"# {label}-{result.tier}\n\n"
        f"Source workload: **{label}**\n\n"
        f"Generated by `workload04_generator.py --avg-size {manifest['target_average_requested_text']}` "
        f"(tool version {wg_common.GENERATOR_VERSION}, seed {result.seed}).\n\n"
        f"- `workload-resources.txt` -- {len(result.resource_lines)} logical request entries, "
        f"same order/MIME distribution/EICAR frequency/1:1 resource identity as the golden "
        f"{label} baseline.\n"
        f"- `manifest.csv` -- {len(result.files)} physical payload files actually generated on disk "
        f"(1 per baseline resource -- no pooling/collapsing).\n"
        f"- `manifest.json` -- full reproducibility record (seed, checksums, scale factor, "
        f"`workload_label`).\n"
        f"- `validation-report.txt` / `.json` -- automatic post-generation validation (see Overall: line).\n"
        f"- `diversity-report.json`, `size-report.json` -- focused sub-reports.\n"
        f"- `httpstorm-config.ini` -- ready-to-use `path_file`/`path_root` config snippet.\n\n"
        f"Overall validation: **{report['overall']}**\n"
    )
    (out / "README.md").write_text(readme, encoding="utf-8")

